title: /r/HardwareSwapUK 
author: HWSUK Mods
email: hwsuk@monotron.me
description: > # this means to ignore newlines until "show_exerpts:"
  Frequently asked questions for the /r/HardwareSwapUK hardware-swapping community.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: /r/HardwareSwapUK FAQ
  tagline: Get answers to all of the simple stuff here.
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  hwsuk/faq
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed