title: /r/HardwareSwapUK 
author: HWSUK Mods
email: hwsuk@monotron.me
description: > # this means to ignore newlines until "show_exerpts:"
  Frequently asked questions for the /r/HardwareSwapUK hardware-swapping community.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /:title/
texture:
  title: /r/HardwareSwapUK FAQ
  tagline: >
    Welcome to the HWSUK FAQ site.<br /><br />
    Here you can get answers to all of the simple stuff such as postage tips, sales etiquette and more. The links below will provide all the information we have collected from community sources to give you an easier format to read and learn some of the more useful information we can provide.
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed