title: My Blog
author: fooMan
email: fooman.in@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  I share here my learning and views.
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: fooMan
  tagline: Programmer. Reader
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    email: fooman.in@gmail.com
    # twitter:
    # quora:
    # github:  
    # linkedIn: 
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

collections:
  types:
    output: true

# Handling Reading
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown            : kramdown